# This is a basic workflow to help you get started with Actions

name: CI-DEPLOYMENT-UAPI

# Controls when the workflow will run
on: [push]
  # Triggers the workflow on push or pull request events but only for the "main" branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-selfhosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/uapi@v3

      # Runs a single command using the runners shell
      - name: Download a Build Artifact
        with:
          name: Parts
          path: ${{github.workspace}}

      # Runs a set of commands using the runners shell
      - name: Run Powershell
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ github.workspace }}."
